version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: locker24_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: locker24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - locker24_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: locker24_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@locker24.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - db
    networks:
      - locker24_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  locker24_network:
    driver: bridge
